org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
ksp.incremental=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.java.home=C:\\Program Files\\Unity\\Hub\\Editor\\6000.0.40f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\OpenJDK


